version: '3.2'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - foodgram_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: mtedoradze/foodgram:v0.1
    restart: always
    volumes:
      - static_value:/app/backend-static/
      - media_value:/app/backend-media/

    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend-static/
      - media_value:/var/html/backend-media/

    depends_on:
      - frontend

volumes:
  foodgram_data:
  static_value:
  media_value:
