# Generated by Django 3.2.16 on 2022-12-05 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ингредиента')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('measure_unit', models.CharField(max_length=50, verbose_name='Единицы измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тега')),
                ('color_code', models.CharField(max_length=16, verbose_name='Цветовой HEX-код')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Текстовое описание')),
                ('image', models.ImageField(upload_to='recipes/images/', verbose_name='Картинка')),
                ('tag', models.TextField(choices=[('', '')], verbose_name='Тег')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
                ('ingredients', models.ManyToManyField(choices=[('', '')], related_name='recipes', to='recipes.Ingredient', verbose_name='Ингредиенты')),
            ],
        ),
    ]
