# Generated by Django 3.2.16 on 2022-12-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(choices=[('', '')], null=True, related_name='recipes', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
