# Generated by Django 3.2.16 on 2022-12-13 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(choices=[('Молоко', 'milk'), ('Яйцо', 'egg'), ('Мука', 'four')], through='recipes.RecipeIngredient', to='recipes.Ingredient', verbose_name='Продукты для приготовления блюда по рецепту'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(choices=[('Завтрак', 'breakfast'), ('Обед', 'lunch'), ('Ужин', 'dinner')], through='recipes.RecipeTag', to='recipes.Tag', verbose_name='Тег'),
        ),
    ]
