# Generated by Django 3.2.16 on 2022-12-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221210_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.CharField(max_length=128),
        ),
    ]
