# Generated by Django 3.2.16 on 2022-12-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20221212_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='author',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.CharField(max_length=128),
        ),
    ]
