# Generated by Django 3.2.16 on 2022-12-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20221213_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(default=None, verbose_name='Количество'),
        ),
    ]
