# Generated by Django 3.2.16 on 2022-12-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredient_name'),
        ('recipes', '0008_auto_20221220_1939'),
    ]

    operations = [
    ]
