# Generated by Django 3.2.16 on 2022-12-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20221221_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(default=None, null=True, verbose_name='Количество'),
        ),
    ]
