# Generated by Django 3.2.16 on 2022-12-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
    ]
