# Generated by Django 3.2.16 on 2022-12-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20221221_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(choices=[('1', 'breakfast'), ('2', 'lunch'), ('3', 'dinner')], through='recipes.RecipeTag', to='recipes.Tag', verbose_name='Тег'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('text',), name='unique_recipe_text'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_recipe_name'),
        ),
    ]
