# Generated by Django 3.2.16 on 2022-12-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20221221_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.IntegerField(choices=[('1', 'breakfast'), ('2', 'lunch'), ('3', 'dinner')], primary_key=True, serialize=False),
        ),
    ]
