# Generated by Django 3.2.16 on 2022-12-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20221222_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'ordering': ('-recipe__pub_date',)},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('-recipe__pub_date',)},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'ordering': ('-recipe__pub_date',)},
        ),
        migrations.AlterModelOptions(
            name='shoppingcartrecipe',
            options={'ordering': ('-recipe__pub_date',)},
        ),
    ]
