# Generated by Django 3.2.16 on 2023-01-10 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Количество'),
        ),
    ]
