# Generated by Django 3.2.16 on 2022-12-13 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221213_2015'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_recipes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shopping_cart',
        ),
        migrations.AlterField(
            model_name='user',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.subscription'),
        ),
    ]
