# Generated by Django 3.2.16 on 2022-12-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20221212_1059'),
        ('users', '0004_user_subcriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subcriptions',
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='recipes.subscription'),
        ),
    ]
